### ISSUE TITLE
The Go program terminated unexpectedly...

### ISSUE THREAD

**Issue by ringworld3702** [pangafu/Hybrid_LeelaZero#6]
[https://prnt.sc/ima0cc](https://prnt.sc/ima0cc)

How to fix it?

**Comment by ringworld3702** [comment]
https://prnt.sc/ima0cc

**Comment by ringworld3702** [comment]
The picture above contains five files in a folder.


http://prntscr.com/imaaf0
This picture contains two files in a folder, but the screen that appears is different.

And I don't know how much I should set the RandomInherit value. What number do you set?

**Comment by ringworld3702** [comment]
I solved a problem with a terminated error by checking the execution as an administrator in the gogui-twogtp.exe file.

But the only problem is, as a result of matches, only one side always wins with a 100 % winning rate.

https://prnt.sc/imb4wp

**Comment by ringworld3702** [comment]
Whether I set 500 match games or play out 3200, there is always the 100% winning rate result in 1~2 second. I guess that problem is the gogui-twogtp file.

**Comment by ringworld3702** [comment]
I have solved. It was not problem with gogui-twogtp file.

**Comment by pangafu** [comment]
@ringworld3702 ^_^

**Comment by pangafu** [comment]
I think maybe the parameter of leela is wrong

**Comment by zyrf-cl** [comment]
I have the same problem as you. How did you solve it？
